services:
  - type: web
    name: bybrawo
    env: node
    buildCommand: |
      npm install
      cd client && npm install
      cd client && chmod +x node_modules/.bin/react-scripts
      cd client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false 